### ISSUE TITLE
Evaluate error message only after assertion failure in assertEqual

### ISSUE THREAD

**Issue by klntsky** [purescript/purescript-assert#10]
Another thing that bothers me a little is that the full error message in `assertEqual` gets evaluated even if it is not needed. `show` can be quite expensive for large inputs.

Possible fix is to delay the first argument of `assert'`  (some renaming should also be done to avoid breaking the API)

```
foreign import assert'
  :: (Unit -> String)
  -> Boolean
  -> Effect Unit
```

Should I make a PR for this issue, or is it too insignificant to care about?

**Comment by garyb** [comment]
It's not really something I've ever had a problem with personally, printing massive things when assertions fail is probably not so useful when it comes to resolving them :wink:

**Comment by garyb** [comment]
I'll close this for now, we can reopen it if it is a more common concern than I thought.
